### ISSUE TITLE
Formula for the RGB^2 color interpolation

### ISSUE THREAD

**Issue by determin1st** [scottsievert/pyohiotalk#1]
If i have color1 and color2, your formula approximates only the middle point.
What about any other position in between?

**Comment by stsievert** [comment]
You're referring to this graph?

<img width="817" alt="screen shot 2018-05-27 at 10 21 12 am" src="https://user-images.githubusercontent.com/1320475/40587648-b088cf30-61c1-11e8-837a-75128b887335.png">

I blurred with a gaussian filter. I set the left/right halves as red/green, and then did a gaussian blur with some sigma. I blurred in a variety of color spaces: https://stsievert.com/blog/2015/04/23/image-sqrt/

**Comment by determin1st** [comment]
I'm referring to this (second blend):

![this](https://stsievert.com/images/posts/computer-color-broken/figures/blur.png)

But when you go from RED to GREEN it's a single step, the final formula should be continuous not discrete, I mean, common RGB blending formula looks like:

```
R = R1 + (R2 - R1) * scale
G = ...
B = ...
```

If scale == 0.5, then it half way to final Red component (of the green color), R2. It may be written as:

```
R = (R1 + R2) / 2
```

There is no square root because I use it for animation without any external source. I tried to look at
```
R = Math.sqrt (R1*R1 + R2*R2) / 2
G = ...
B = ...
```
and it gave the same color as in your second case (where Math.sqrt (x + y) / 2)...

**Comment by determin1st** [comment]
Oh.. I found it.. It should be:

```
R = Math.sqrt(R1**2 + (R2**2 - R1**2) * scale) | 0
G = Math.sqrt(G1**2 + (G2**2 - G1**2) * scale) | 0
B = Math.sqrt(B1**2 + (B2**2 - B1**2) * scale) | 0
```

Thanks for information, good work of yours.

**Comment by determin1st** [comment]
https://rawgit.com/determin1st/redsock/master/test-4/index.html

it's a color transition test where that formula is implemented. clicking buttons in the process will pause/continue it.

**Comment by stsievert** [comment]
Yup, it's a linear combination in the squared space, then takes the square root to bring back to RGB. The number of photons is proportional to the square of R, G or B. Mixing in the original photon space makes sense.

 Also, nice animation. I haven't seen that before.
